name: Repo-Clean

on:
  workflow_dispatch:
    inputs:
      delete_actions_caches:
        description: 'Delete Actions Caches? (yes/no)'
        required: true
        default: 'no'
      delete_commit_history:
        description: 'Delete commit history? (yes/no)'
        required: true
        default: 'no'
      delete_runs_and_releases:
        description: 'Delete releases and workflow runs? (yes/no)'
        required: true
        default: 'no'
      releases_keep_latest:
        description: "How many latest releases to keep. (0 = none, false = skip)"
        required: false
        default: "0"
        type: choice
        options:
          - false
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 20
          - 30
      workflows_keep_day:
        description: "Days to keep workflows. (0 = none, false = skip)"
        required: false
        default: "0"
        type: choice
        options:
          - false
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 20
          - 30
      delete_tags:
        description: "Delete related Tags?"
        required: false
        default: "true"
        type: choice
        options:
          - true
          - false
      prerelease_option:
        description: "Whether to differentiate pre-release."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - true
          - false
      releases_keep_keyword:
        description: "Keyword of the keep releases."
        required: false
        default: "Backup/backup/BACKUP"
      workflows_keep_keyword:
        description: "keywords for keep workflows."
        required: false
        default: ""
      out_log:
        description: "Output detailed JSON logs."
        required: false
        default: false
        type: boolean

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Delete Actions Caches
      if: contains('yes.YES.Yes', inputs.delete_actions_caches)
      run: gh cache delete --all --succeed-on-no-caches

    - name: Delete all contents in release branch
      if: contains('yes.YES.Yes', inputs.delete_commit_history)
      run: |
        set -e
        # 确认远端是否已有 release 分支
        if git ls-remote --exit-code --heads origin release >/dev/null 2>&1; then
          echo "Remote branch 'release' exists. Checking out..."
          git checkout release
        else
          echo "Remote branch 'release' does not exist. Creating..."
          git checkout -b release
        fi
        # 确保拉取最新（如果存在）
        git pull --ff-only origin release || true

        echo "Removing all files..."
        # 删除所有已跟踪与未跟踪文件（保留 .git 目录）
        git rm -r --cached . >/dev/null 2>&1 || true
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

        # 若需要保留某些文件，可在此添加白名单逻辑，例如：
        # git checkout HEAD -- README.md

        # 确认是否真的有变更
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit (already empty)."
        else
          git add -A
          git commit -m "chore: clear all contents in release branch"
          git push origin release
        fi

        echo "Release branch content cleared."

    - name: Delete releases and workflows runs
      if: contains('yes.YES.Yes', inputs.delete_runs_and_releases)
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: ${{ inputs.releases_keep_latest != 'false' }}
        delete_tags: ${{ inputs.delete_tags }}
        prerelease_option: ${{ inputs.prerelease_option }}
        releases_keep_latest: ${{ inputs.releases_keep_latest }}
        releases_keep_keyword: ${{ inputs.releases_keep_keyword }}
        delete_workflows: ${{ inputs.workflows_keep_day != 'false' }}
        workflows_keep_day: ${{ inputs.workflows_keep_day }}
        workflows_keep_keyword: ${{ inputs.workflows_keep_keyword }}
        out_log: ${{ inputs.out_log }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
